Fix bug: can't find file under Mac.

diff --git a/bin/csct b/bin/csct
--- a/bin/csct
+++ b/bin/csct
@@ -1,27 +1,28 @@
 #!/bin/bash
 
-version=1.0.2
-date=2012-06-09
+version=1.0.3
+date=2012-06-23
 
 top=`pwd`
+systype=`uname -s`
 cs_file=cscope.files
 lookup_file=filenametags
 clean_file_list="$cs_file cscope.in.out cscope.po.out cscope.out tags $lookup_file"
 
 function gen_file_list()
 {
-	local _file_list=$@
+	local _dir="$1"
 	
-	rm -f $cs_file
-	for _file in $_file_list; do
-		if [ -f $_file ]; then
-			echo $top/$_file >> $cs_file
-		elif [ -d $_file ]; then
-			find $top/$_file -regex ".*\.\(h\|c\|cpp\|java\)" -type f >> $cs_file 2>/dev/null
-		else
-			echo "Warning: ignore \`$_file'" >&2
+	if [ -d "$_dir" ]; then
+		if [ $systype = Linux ]; then
+			find "$_dir" -regex ".*\.\(h\|c\|cpp\|java\)" -type f > $cs_file 2>/dev/null
+		elif [ $systype = Darwin ]; then
+			find -E "$_dir" -regex ".*\.(h|c|cpp|java)" -type f > $cs_file 2>/dev/null
 		fi
-	done
+	else
+		echo "Error: \`$_file' is not a directory or does not exist!" >&2
+		exit 1
+	fi
 }
 
 function gen_symbol_list()
